name: stock-track-jetson
channels:
  - defaults
dependencies:
  - python=3.14
  - pip
  - pip:
    - numpy
    - pandas
    - torch
    - torchvision
    - scikit-learn
    - matplotlib
    - jupyter
    - pytest
    - yfinance
    - onnxscript

